apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argo
spec:
  project: helm
  source:
    repoURL:  git@<repo>
    targetRevision: <branch>
    path: ClusterAutoscaler
    directory:
      recursive: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true 
    automated:
      selfHeal: true
