apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo
spec:
  project: helm
  source:
    repoURL:  https://grafana.github.io/helm-charts
    targetRevision: 7.3.0
    chart: grafana
    helm:
      releaseName: grafana
      parameters:
        - name: persistence.enabled
          value: "true"
        - name: persistence.size
          value: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true 
