apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo
spec:
  project: helm
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 20.1.0
    chart: prometheus
    helm:
      releaseName: prometheus
      parameters:
        - name: alertmanager.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
